name = input ("what is your name? ")
print("hello " + name) 
birth_year = input ("enter your birth year: " )
Age = 2023 - int (birth_year)
print("your age is " , Age)
std = input ("in which class are you studying? ")
print("you are studying in " + std)
School = input ("what is your school name? ") 
print("your school name is " + School)
